### ISSUE TITLE
Configure better icons for bottom tabs

### ISSUE THREAD

**Issue by devcer** [devcer/CapShun#5]
* [ ] Three tabs right now - Home, Captions, Settings. Suggest better icons for them.

**Comment by ampsteric** [comment]
I would like to work on this issue sir. please assign it to me.

**Comment by devcer** [comment]
@ampsteric Done. All the best.

**Comment by ampsteric** [comment]
for settings I would suggest using this:
![settings](https://user-images.githubusercontent.com/56419358/94540752-718d4180-0264-11eb-920e-bacd7574c4da.PNG)
for captions I would suggest using this:
![captions](https://user-images.githubusercontent.com/56419358/94540756-72be6e80-0264-11eb-97e6-38f33a07a5f1.PNG)
for home I would suggest using this:
![home](https://user-images.githubusercontent.com/56419358/94540765-75b95f00-0264-11eb-85eb-fe7045f6d720.PNG)

**Comment by devcer** [comment]
Home and Settings look good! but think of another icon for captions. Captions here are captions for Instagram/Facebook posts. Integrate your changes to this file https://github.com/devcer/CapShun/blob/master/src/navigation/BottomTabNavigator.tsx and submit an MR to master

**Comment by ampsteric** [comment]
okay. I will surely do that.

**Comment by ampsteric** [comment]
resolved #5.
please review and accept my PR and allow me to be a contributor for CapShun and Hacktoberfest as well.

best regards,
ampsteric

**Comment by ampsteric** [comment]
It is my humble request to the maintainers to please label my PR as "hacktoberfest-accepted" or mark the repo with the "hacktoberfest"  topic so that it can be counted as a valid PR for my first hacktoberfest.

best regards,
ampsteric

**Comment by devcer** [comment]
@ampsteric This repo is already marked with Hacktoberfest. so no worries.
